- hosts: localhost
  user: root
  gather_facts: yes

  roles:
    - external.deploy

    - kernel-tune
    - nginx.log-format
    - external.benchmarker
    - external.benchmark-worker
    - external.shipment
    - external.payment

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - benchmark-worker.service
