- hosts: localhost
  user: root
  gather_facts: yes

  roles:
    - bootstrap
    - aliyun
    - dev.deploy

    - kernel-tune
    - nginx
    - nginx.log-format
    - golang
    - external.nginx
    - external.shipment
    - external.payment
