- hosts: localhost
  user: root
  gather_facts: yes

  roles:
    - bootstrap
    - docker
    - initial-data
    - aliyun
    - webapp.deploy

    - nginx
    - mysql
    - golang
    - python
    - webapp.mysql
    - webapp.golang
    - webapp.python
    - webapp.nginx

    - external.deploy
    - kernel-tune
    - nginx.log-format
    - external.benchmarker
    - external.benchmark-worker
    - external.shipment
    - external.payment
